RockLib.HealthChecks.AspNetCore/HealthCheckMiddleware.cs, RockLib.HealthChecks.AspNetCore/HealthCheckMiddlewareExtensions.cs, RockLib.HealthChecks.AspNetCore/IResponseFormatter.cs, RockLib.HealthChecks.AspNetCore/NewtonsoftJsonResponseFormatter.cs, RockLib.HealthChecks/DependencyInjection/IHealthCheckRunnerBuilder.cs
Adding this abstraction should allow a future UIResponseFormatter implementation.
=> Add IReponseFormatter abstraction to AspNetCore project

RockLib.HealthChecks.AspNetCore.ResponseWriter/appveyor.yml, RockLib.HealthChecks.AspNetCore/appveyor.yml, RockLib.HealthChecks.Client/appveyor.yml, RockLib.HealthChecks.HttpModule/appveyor.yml, RockLib.HealthChecks.WebApi/appveyor.yml, RockLib.HealthChecks/appveyor.yml
Cycling keys for deploying new packages.
=> Update keys from Appveyor

RockLib.HealthChecks.Client/.editorconfig, RockLib.HealthChecks.Client/CHANGELOG.md, RockLib.HealthChecks.Client/Directory.Build.props, RockLib.HealthChecks.Client/HealthCheckResult.cs, RockLib.HealthChecks.Client/HealthCheckResultJsonConverter.cs, RockLib.HealthChecks.Client/HealthResponse.cs, RockLib.HealthChecks.Client/NullableAttributes.cs, RockLib.HealthChecks.Client/RockLib.HealthChecks.Client.csproj, RockLib.HealthChecks.Client/appveyor.yml, Tests/RockLib.HealthChecks.Client.Tests/.editorconfig, Tests/RockLib.HealthChecks.Client.Tests/AssemblySettings.cs, Tests/RockLib.HealthChecks.Client.Tests/DeserializeTests.cs, Tests/RockLib.HealthChecks.Client.Tests/Directory.Build.props, Tests/RockLib.HealthChecks.Client.Tests/RockLib.HealthChecks.Client.Tests.csproj
Updating code in `RockLib.HealthChecks.Client` to standards
=> Update to standards

.github/workflows/snyk-test.yml
=> added generic workflows

docs/AspNetCore.md, docs/ConfigureAppSettings.md, docs/ConfigureNet451AndAbove.md, docs/ConfigureNet45AndBelow.md, docs/CustomHealthCheck.md, docs/DiskDriveHealthCheck.md, docs/GettingStarted.md, docs/HttpModule.md, docs/InstantiateRunner.md, docs/ManualHealthChecks.md, docs/ProcessUptimeHealthCheck.md, docs/ResponseWriter.md, docs/SystemUptimeHealthCheck.md, docs/WebApi.md
changes:
- added front matter 
- fix headings
- change language
- cleanup
=> Documentation updates

RockLib.HealthChecks.WebApi/.editorconfig, RockLib.HealthChecks.WebApi/CHANGELOG.md, RockLib.HealthChecks.WebApi/Directory.Build.props, RockLib.HealthChecks.WebApi/HealthCheckHandler.cs, RockLib.HealthChecks.WebApi/HealthCheckHandlerExtensions.cs, RockLib.HealthChecks.WebApi/RockLib.HealthChecks.WebApi.csproj, RockLib.HealthChecks.WebApi/RockLib.HealthChecks.WebApi.sln, Tests/RockLib.HealthChecks.WebApi.Tests/.editorconfig, Tests/RockLib.HealthChecks.WebApi.Tests/AssemblySettings.cs, Tests/RockLib.HealthChecks.WebApi.Tests/Directory.Build.props, Tests/RockLib.HealthChecks.WebApi.Tests/HealthCheckHandlerExtensionsTests.cs, Tests/RockLib.HealthChecks.WebApi.Tests/HealthCheckHandlerTests.cs, Tests/RockLib.HealthChecks.WebApi.Tests/RockLib.HealthChecks.WebApi.Tests.csproj
Updated the WebApi library and added tests.
=> Modernized Library and Added Tests

RockLib.HealthChecks.AspNetCore.ResponseWriter/.editorconfig, RockLib.HealthChecks.AspNetCore.ResponseWriter/CHANGELOG.md, RockLib.HealthChecks.AspNetCore.ResponseWriter/Directory.Build.props, RockLib.HealthChecks.AspNetCore.ResponseWriter/RockLib.HealthChecks.AspNetCore.ResponseWriter.csproj, RockLib.HealthChecks.AspNetCore.ResponseWriter/RockLib.HealthChecks.AspNetCore.ResponseWriter.sln, RockLib.HealthChecks.AspNetCore.ResponseWriter/RockLibHealthChecks.cs, Tests/RockLib.HealthChecks.AspNetCore.ResponseWriter.Tests/.editorconfig, Tests/RockLib.HealthChecks.AspNetCore.ResponseWriter.Tests/Directory.Build.props, Tests/RockLib.HealthChecks.AspNetCore.ResponseWriter.Tests/ResponseWriterTests.cs, Tests/RockLib.HealthChecks.AspNetCore.ResponseWriter.Tests/RockLib.HealthChecks.AspNetCore.ResponseWriter.Tests.csproj
Updated the ResponseWriter project to current standards.
=> Modernize ResponseWriter

RockLib.HealthChecks/RockLib.HealthChecks.csproj
Updated the package version for HealthChecks
- Will this change require an update to an example project? (if …
=> Update HealthChecks package version

RockLib.HealthChecks.AspNetCore.ResponseWriter/CHANGELOG.md, RockLib.HealthChecks.AspNetCore.ResponseWriter/RockLib.HealthChecks.AspNetCore.ResponseWriter.csproj, RockLib.HealthChecks.AspNetCore/CHANGELOG.md, RockLib.HealthChecks.AspNetCore/RockLib.HealthChecks.AspNetCore.csproj, RockLib.HealthChecks.HttpModule/CHANGELOG.md, RockLib.HealthChecks.HttpModule/RockLib.HealthChecks.HttpModule.csproj, RockLib.HealthChecks.WebApi/CHANGELOG.md, RockLib.HealthChecks.WebApi/RockLib.HealthChecks.WebApi.csproj
This updates all the packages that have a dependency on RockLib.HealthChecks to the most current version.
**2. Bug fix (non-breaking change that fixes an issue)** …
=> Updated RockLib.HealthChecks dependency to 2.0.1

RockLib.HealthChecks.AspNetCore/CHANGELOG.md, RockLib.HealthChecks.AspNetCore/RockLib.HealthChecks.AspNetCore.csproj
Updated RockLib.HealthChecks.AspNetCore to `3.0.0-alpha.2` for release
- Will this change require an update …
=> Release new version of RockLib.HealthChecks.AspNetCore

RockLib.HealthChecks.WebApi/CHANGELOG.md, RockLib.HealthChecks.WebApi/RockLib.HealthChecks.WebApi.csproj
Updated RockLib.HealthChecks.WebApi to `2.0.0-alpha.2`
- Will this change require an update to an example …
=> Release for RockLib.HealthChecks.WebApi 2.0.0-alpha.2

RockLib.HealthChecks.AspNetCore/CHANGELOG.md, RockLib.HealthChecks.AspNetCore/RockLib.HealthChecks.AspNetCore.csproj
This will release RockLib.HealthChecks 3.0.0. This has been tested in an application and is fully functional.
**1. Non-functional change (e.g. documentation changes, removing unused `using` directives, renaming local variables, etc)**
- Have you made corresponding changes to the …
=> Release RockLib.HealthChecks.AspNetCore 3.0.0

RockLib.HealthChecks/CHANGELOG.md, RockLib.HealthChecks/DependencyInjection/DependencyInjectionExtensions.cs, RockLib.HealthChecks/DependencyInjection/HealthCheckRunnerBuilder.cs, RockLib.HealthChecks/Directory.Build.props, RockLib.HealthChecks/HealthCheckExtensions.cs, RockLib.HealthChecks/HealthCheckRunner.cs, RockLib.HealthChecks/RockLib.HealthChecks.csproj, RockLib.HealthChecks/System/DependencyInjectionExtensions.cs, RockLib.HealthChecks/System/DiskDriveHealthCheck.cs, RockLib.HealthChecks/System/ProcessUptimeHealthCheck.cs, RockLib.HealthChecks/System/SystemUptimeHealthCheck.cs, Tests/RockLib.HealthChecks.Tests/Directory.Build.props, Tests/RockLib.HealthChecks.Tests/HealthCheckResultTests.cs, Tests/RockLib.HealthChecks.Tests/SingleResultHealthCheckTests.cs
update target frameworks to remove .NET Core 3.1 and add .NET 8
=> Update to .NET 8 and Remove .NET Core 3.1

Tests/RockLib.HealthChecks.AspNetCore.Tests/Directory.Build.props, Tests/RockLib.HealthChecks.AspNetCore.Tests/HealthCheckMiddlewareTests.cs, Tests/RockLib.HealthChecks.AspNetCore.Tests/NewtonsoftJsonResponseFormatterTests.cs, Tests/RockLib.HealthChecks.AspNetCore.Tests/RockLib.HealthChecks.AspNetCore.Tests.csproj
update target frameworks to remove .NET Core 3.1 and add .NET 8 (test project)
=> Update to .NET 8 and Remove .NET Core 3.1 (test project)

RockLib.HealthChecks/CHANGELOG.md, RockLib.HealthChecks/RockLib.HealthChecks.csproj
=> Update to .NET 8 and Remove .NET Core 3.1 - full release

RockLib.HealthChecks.AspNetCore.ResponseWriter/RockLib.HealthChecks.AspNetCore.ResponseWriter.csproj, RockLib.HealthChecks.AspNetCore/RockLib.HealthChecks.AspNetCore.csproj, RockLib.HealthChecks.WebApi/RockLib.HealthChecks.WebApi.csproj
- RockLib.HealthChecks.AspNetCore.ResponseWriter
- RockLib.HealthChecks.AspNetCore
- RockLib.HealthChecks.WebApi
=> update to full versions of RockLib.HealthChecks

RockLib.HealthChecks/CHANGELOG.md, RockLib.HealthChecks/RockLib.HealthChecks.csproj
Release RockLib.HealthChecks 3.0.1 to fix vulnerability in RockLib.Configuration 4.0.0, see the [changelog](https://github.com/RockLib/RockLib.Configuration/blob/main/RockLib.Configuration/CHANGELOG.md) for details. 
**2. Bug fix (non-breaking change that fixes an issue)**
- New and …
=> Release RockLib.HealthChecks 3.0.1

RockLib.HealthChecks.Client/CHANGELOG.md, RockLib.HealthChecks.Client/RockLib.HealthChecks.Client.csproj, Tests/RockLib.HealthChecks.Client.Tests/RockLib.HealthChecks.Client.Tests.csproj
This updates System.Text.Json -> 8.0.5 to fix a vulnerability.
---
<sup>_[Reviewer guidelines](../blob/main/CONTRIBUTING.md#reviewing-changes)_</sup>
=> Release RockLib.HealthChecks.Client 2.0.2

RockLib.HealthChecks.AspNetCore.ResponseWriter/CHANGELOG.md, RockLib.HealthChecks.AspNetCore.ResponseWriter/RockLib.HealthChecks.AspNetCore.ResponseWriter.csproj, RockLib.HealthChecks.AspNetCore/CHANGELOG.md, RockLib.HealthChecks.AspNetCore/RockLib.HealthChecks.AspNetCore.csproj, RockLib.HealthChecks.HttpModule/CHANGELOG.md, RockLib.HealthChecks.HttpModule/RockLib.HealthChecks.HttpModule.csproj, RockLib.HealthChecks.WebApi/CHANGELOG.md, RockLib.HealthChecks.WebApi/RockLib.HealthChecks.WebApi.csproj
Release the RockLib.HealthChecks suite of libraries. 
**2. Bug fix (non-breaking change that fixes an issue)
3. New feature (non-breaking change that adds functionality)**
- Will this change require an update to an example project? (if so, create an issue and link to it)
---
<sup>_[Reviewer guidelines](../blob/main/CONTRIBUTING.md#reviewing-changes)_</sup>
=> Release RockLib.HealthCheck dependent packages

Examples/Example.HealthChecks.AspNetCore.ResponseWriter/Example.HealthChecks.AspNetCore.ResponseWriter.csproj, Examples/Example.HealthChecks.AspNetCore/Example.HealthChecks.AspNetCore.csproj, Examples/Example.HealthChecks.Client/Example.HealthChecks.Client.csproj, RockLib.HealthChecks.AspNetCore.ResponseWriter/Directory.Build.props, RockLib.HealthChecks.AspNetCore/Directory.Build.props, RockLib.HealthChecks.Client/CHANGELOG.md, RockLib.HealthChecks.Client/Directory.Build.props, RockLib.HealthChecks.Client/RockLib.HealthChecks.Client.csproj, RockLib.HealthChecks.HttpModule/Directory.Build.props, RockLib.HealthChecks.WebApi/Directory.Build.props, RockLib.HealthChecks/CHANGELOG.md, RockLib.HealthChecks/Directory.Build.props, RockLib.HealthChecks/HealthCheck.cs, RockLib.HealthChecks/RockLib.HealthChecks.csproj, Tests/RockLib.HealthChecks.AspNetCore.ResponseWriter.Tests/Directory.Build.props, Tests/RockLib.HealthChecks.AspNetCore.Tests/Directory.Build.props, Tests/RockLib.HealthChecks.Client.Tests/Directory.Build.props, Tests/RockLib.HealthChecks.Client.Tests/RockLib.HealthChecks.Client.Tests.csproj, Tests/RockLib.HealthChecks.Tests/Directory.Build.props, Tests/RockLib.HealthChecks.Tests/RockLib.HealthChecks.Tests.csproj
=> Remove .NET 6 for HealthChecks

RockLib.HealthChecks.Client/CHANGELOG.md, RockLib.HealthChecks.Client/RockLib.HealthChecks.Client.csproj
=> Update Client Package to Alpha

RockLib.HealthChecks.AspNetCore.ResponseWriter/CHANGELOG.md, RockLib.HealthChecks.AspNetCore.ResponseWriter/RockLib.HealthChecks.AspNetCore.ResponseWriter.csproj, RockLib.HealthChecks.AspNetCore/CHANGELOG.md, RockLib.HealthChecks.AspNetCore/RockLib.HealthChecks.AspNetCore.csproj, RockLib.HealthChecks.HttpModule/CHANGELOG.md, RockLib.HealthChecks.HttpModule/RockLib.HealthChecks.HttpModule.csproj, RockLib.HealthChecks.WebApi/CHANGELOG.md, RockLib.HealthChecks.WebApi/RockLib.HealthChecks.WebApi.csproj, Tests/RockLib.HealthChecks.AspNetCore.ResponseWriter.Tests/RockLib.HealthChecks.AspNetCore.ResponseWriter.Tests.csproj, Tests/RockLib.HealthChecks.AspNetCore.Tests/RockLib.HealthChecks.AspNetCore.Tests.csproj
=> Update Dependent Packages to Alphas

RockLib.HealthChecks.Client/CHANGELOG.md, RockLib.HealthChecks.Client/RockLib.HealthChecks.Client.csproj, RockLib.HealthChecks/CHANGELOG.md, RockLib.HealthChecks/RockLib.HealthChecks.csproj
=> Updated Root Packages for Final Versions
